---
title: "Lab 6 R functions"
author: "Weixi Chen"
date: "10/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# This is heading 1
This is my work from Lab6 in **BIMM143**.

```{r}
# this is to demo a code chunk
plot(1:10)
```

## Practice reading files (again...)
```{r}
read.csv("test1.txt")
read.csv("test2.txt", sep="$")
read.table("test3.txt")
```

## Practice R functions
```{r}
add <- function(x, y=1) {
  # Sum the input x and y
  x+y
  }
```

```{r}
add(1)
# change the value of y
add(x=1, y=4)
add(1,4)
# add on vector
add(c(1,2,3))
add(c(1,2,3),4)
```

## SectionA
```{r}
df <- data.frame(a=1:10, b=seq(200,400,length=10),c=11:20,d=NA) 
```

```{r}
rescale <- function(x){
  # na.rm=TRUE should be added in range to omit NAs in data.frame
  rng <- range(x, na.rm=TRUE)
  (x-rng[1])/(rng[2]-rng[1])
}
```

```{r}
rescale(df$a)
rescale(df)
```

```{r}
rescale2 <- function(x, na.rm=TRUE, plot=FALSE) {
 rng <-range(x, na.rm=na.rm)
 # If function is defined, put return function at very end
 answer <- (x - rng[1]) / (rng[2] - rng[1])
 # If you want to change default setting, put if function
 if(plot) {
 plot(answer, typ="b", lwd=4)
 }
 print("Hello")
 print("is it me you are looking for?")
 print("I can see it in ...")
 return(answer)
}
```

```{r}
rescale2(c(1,2,3,4,NA), plot=TRUE)
```
