---
title: "Lab 8"
author: "Weixi Chen"
date: "10/24/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## k-means clustering
(able to see number of cluster on plot)
```{r}
# Generate some example data for clustering
tmp <- c(rnorm(30,-3), rnorm(30,3))
x <- cbind(x=tmp, y=rev(tmp))
colnames(x) <- c("x","y")
# plot the data without clustering
plot(x)
# plot k-means clustering with color
# nstart: running algorithm multiple times helps find the global minimum total within cluster sum of squares, increasing the default value of nstart is often sensible
km <- kmeans(x, centers=2, nstart=20)
km
#Systematically try acrange of different k values and plot a “scree plot” (number of cluster against total within SS), find the "Elbow"
km$tot.withinss
plot(x, col=km$cluster)
```

## Hierarchical clustering
(unable to see number of cluster on plot)
```{r}
# Step 1. Generate some example data for clustering
x <- rbind(
 matrix(rnorm(100, mean=0, sd = 0.3), ncol = 2), # c1
 matrix(rnorm(100, mean = 1, sd = 0.3), ncol = 2), # c2
 matrix(c(rnorm(50, mean = 1, sd = 0.3), # c3
 rnorm(50, mean = 0, sd = 0.3)), ncol = 2))
colnames(x) <- c("x", "y")
# Step 2. Plot the data without clustering
plot(x)
# Step 3. Generate colors for known clusters
# (just so we can compare to hclust results)
col <- as.factor( rep(c("c1","c2","c3"), each=50) )
plot(x, col=col)
```

```{r}
# hierarchical clustering
hc <- hclust(dist(x))
# draw tree
plot(hc)
abline(h=2, col="red")
# cut the tree into cluster
k2 <- cutree(hc, k=2)  # Cut by height h or cut by k group, k2 defines 2 groups
k3 <- cutree(hc, k=3)  # k3 defines 3 groups
#plot hierarchical clustering
plot(x, col=k3)
#how many points in each cluster?
table(k3)
#cross-tabllulate i.e. compare our clustering result with the known cluster
table(k3, col)
```

## Principle Component analysis (PCA) on gene data
```{r}
# read gene expression data
mydata <- read.csv("https://tinyurl.com/expression-CSV",row.names=1)
# check the fist part of the data
head(mydata)
#how many data in this data frame
dim(mydata)
```

```{r}
# Let's do PCA with the prcomp() function
pca <- prcomp(t(mydata), scale=T)
# see what is returned by the prcomp() funcion
attributes(pca)
```

```{r}
# A basic PC1 vs PC2 2-D plot
plot(pca$x[,1], pca$x[,2])
# Varience is often more informative to look at
pca.var <- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100,1)
pca.var
pca.var.per
# summarize in barplot
barplot(pca.var.per, main="Scree Plot",
 xlab="Principal Component", ylab="Percent Variation")
```

```{r}
# plot PCA with color
plot(pca$x[,1], pca$x[,2],
     col=c("red", "red", "red", "red", "red",
           "blue", "blue", "blue", "blue","blue"))
```


## Principle Component analysis (PCA) on UK food data
```{r}
UK <- read.csv("UK_foods.csv", row.names = 1)
head(UK)
dim(UK)
#data preview
View(UK)
```

```{r}
# barplot data
barplot(as.matrix(UK), beside=T, col=rainbow(nrow(UK)))
# compare small data set
pairs(UK, col=rainbow(10), pch=16) # difficult to compare
```

```{r}
# Let's do pca with prcomp() function
pca <- prcomp( t(UK) )
attributes(pca)
summary(pca)
```

```{r}
# Plot PC1 vs PC2
plot(pca$x[,1], pca$x[,2], xlab="PC1", ylab="PC2", xlim=c(-270,500))
#adds text labels over the data points
text(pca$x[,1], pca$x[,2], colnames(UK), col= c("orange","red","blue","green"))
```

```{r}
# how much variation in the original data each PC accounts for
pca.var.per <- round(pca$sdev^2/sum(pca$sdev^2)*100,1)
pca.var.per
# summarize in barplot
barplot(pca.var.per, xlab="Principal Component", ylab="Percent Variation")
```

Variable loadings
```{r}
## Lets focus on PC1 as it accounts for > 90% of variance 
par(mar=c(10, 3, 0.35, 0))
barplot( pca$rotation[,1], las=2 )
biplot(pca)
```

