---
title: "Lab 15"
author: "Weixi Chen"
date: "11/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(DESeq2)
```

```{r}
metaFile <- "GSE37704_metadata.csv"
countFile <- "GSE37704_featurecounts.csv"

# Import metadata and take a peak
colData = read.csv(metaFile, row.names=1)
head(colData)
# Import countdata
countData = read.csv(countFile, row.names=1)
countData <- as.matrix(countData[,-1])
View(countData)
```

```{r}
# test all()
all(c(T,T,F))
```

## remove zero count genes
we want to exclude genes (i.e. rows) where we have 0 read count across all samples (i.e. columns).
```{r}
countData = countData[ rowSums(countData)!=0,]
head(countData)
```

```{r}
# setup the object with our data in the way DESeq wants it
dds = DESeqDataSetFromMatrix(countData=countData,
                            colData=colData,
                            design=~condition)
# run the analysis
dds = DESeq(dds)
dds
```

```{r}
# get result
res= results(dds)
res
```

```{r}
plot(res$log2FoldChange, -log(res$padj))
```

```{r}
# add color
mycols <- rep("gray", length(res$padj))
mycols[abs(res$log2FoldChange)>2] <- "blue"
mycols[abs(res$padj)>0.005&abs(res$log2FoldChange)>2] <- "red"
plot(res$log2FoldChange, -log(res$padj), col=mycols)
```

## adding gene annotation
```{r}
BiocManager::install("AnnotationDbi")
BiocManager::install("org.Hs.eg.db")
```

```{r}
library("AnnotationDbi")
library("org.Hs.eg.db")

# we can translate between all the following database ID systems
columns(org.Hs.eg.db)
```

```{r}
res$symbol = mapIds(org.Hs.eg.db,
                    keys=row.names(countData),# where are my IDs
                    keytype="ENSEMBL",        # what format are my IDs
                    column="SYMBOL",          # the new format I want
                    multiVals="first")
res$entrez = mapIds(org.Hs.eg.db,
                    keys=row.names(countData),
                    keytype="ENSEMBL",
                    column="ENTREZID",
                    multiVals="first")
res$name =   mapIds(org.Hs.eg.db,
                    keys=row.names(res),
                    keytype="ENSEMBL",
                    column="GENENAME",
                    multiVals="first")
head(res,10)
```

## pathway analysis
```{r}
library(pathview)
library(gage)
library(gageData)

data(kegg.sets.hs)
data(sigmet.idx.hs)

# Focus on signaling and metabolic pathways only
kegg.sets.hs = kegg.sets.hs[sigmet.idx.hs]

# Examine the first 3 pathways
head(kegg.sets.hs, 3)
```

```{r}
foldchanges = res$log2FoldChange
names(foldchanges) = res$entrez
head(foldchanges)
```

```{r}
keggres = gage(foldchanges, gsets=kegg.sets.hs)
attributes(keggres)
# Look at the first few down (less) pathways
head(keggres$less)
pathview(gene.data=foldchanges, pathway.id="hsa04110")
```

## section3
```{r}
data(go.sets.hs)
data(go.subs.hs)

# Focus on Biological Process subset of GO
gobpsets = go.sets.hs[go.subs.hs$BP]

gobpres = gage(foldchanges, gsets=gobpsets, same.dir=TRUE)

lapply(gobpres, head)
```




